name: email_scraper
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - beautifulsoup4=4.12.2
  - requests=2.31.0
  - pyyaml=6.0.1
  - lxml=4.9.3
  - pip
  - pip:
    - -r requirements.txt
